#cloud-config

runcmd:
 - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
 - sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
 - yum -y install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos psacct
 - yum -y --enablerepo=epel install ansible pyOpenSSL
 - yum update
 - git clone https://github.com/openshift/openshift-ansible
 - mkdir -p /usr/share/ansible/
 - mv openshift-ansible /usr/share/ansible/
 - cd /usr/share/ansible/openshift-ansible && git checkout -b release-3.9 origin/release-3.9
